Update Release_8668105t_Jenkinsfile

diff --git a/Release_8668105t_Jenkinsfile b/Release_8668105t_Jenkinsfile
--- a/Release_8668105t_Jenkinsfile
+++ b/Release_8668105t_Jenkinsfile
@@ -1,68 +1,68 @@
-agent {
-    node {
-        label 'master'
-    }
-}
-
-tools { 
-    maven 'maven3' 
-}
-
-options {
-    buildDiscarder logRotator( 
-                daysToKeepStr: '15', 
-                numToKeepStr: '10'
-        )
-}
-
-environment {
-    APP_NAME = "STUDENT_APP"
-    APP_ENV  = "DEV"
-}
-
-stages {
-    
-    stage('Stage1') {
-        steps {
-            sh """
-            echo "Stage1_8668106t : Release Environment Preparation Completed"
-            """
+pipeline {
+    agent {
+        node {
+            label 'master'
         }
     }
 
-    stage('Stage2') {
-        steps {
-            sh """
-            docker stop webapp_8668106t || true
-            docker rm webapp_8668106t || true
-            docker run -d --name webapp_8668106t -p 31200:80 wb1_image_8668106t
-            echo "Stage2_8668106t : Release Container webapp_8668106t Created Completed"
-            """
-        }
+    tools { 
+        maven 'maven3' 
     }
 
-    stage('Stage3') {
-        parallel {
-            stage('API Test') {
-                steps {
-                    sh """
-                    echo "Stage3_8668106t: API Test Completed"
-                    """
-                }
-            }
-            stage('Scan Test') {
-                steps {
-                    sh """
-                    echo "Stage3_8668106t: Scan Test Completed"
-                    """
-                }
+    options {
+        buildDiscarder logRotator( 
+                    daysToKeepStr: '15', 
+                    numToKeepStr: '10'
+            )
+    }
+
+    environment {
+        APP_NAME = "STUDENT_APP"
+        APP_ENV  = "DEV"
+    }
+
+    stages {
+        
+        stage('Stage1') {
+            steps {
+                sh """
+                echo "Stage1_8668106t : Release Environment Preparation Completed"
+                """
             }
         }
-    }
 
-    stage('Stage4') {
-        steps {
-            script {
+        stage('Stage2') {
+            steps {
+                sh """
+                docker stop webapp_8668106t || true
+                docker rm webapp_8668106t || true
+                docker run -d --name webapp_8668106t -p 31200:80 wb1_image_8668106t
+                echo "Stage2_8668106t : Release Container webapp_8668106t Created Completed"
+                """
+            }
+        }
+
+        stage('Stage3') {
+            parallel {
+                stage('API Test') {
+                    steps {
+                        sh """
+                        echo "Stage3_8668106t: API Test Completed"
+                        """
+                    }
+                }
+                stage('Scan Test') {
+                    steps {
+                        sh """
+                        echo "Stage3_8668106t: Scan Test Completed"
+                        """
+                    }
+                }
+            }
+        }
+
+        stage('Stage4') {
+            steps {
                 def userInput = input(
                     message: "8668106t, proceed to release the work to next phase?",
                     ok: "Proceed",
@@ -72,23 +72,22 @@ stages {
                 )
                 if (userInput) {
                     echo "Stage5_8668106t : Work Release – Proceeds to Next Phase"
-                    env.STAGE_NAME = 'Stage5'
                 } else {
                     echo "Stage5_8668106t : Work Release - Stops"
-                    env.STAGE_NAME = 'Stage4'
                 }
             }
         }
-    }
 
-    stage('Stage5') {
-        when {
-            expression {
-                return env.STAGE_NAME == 'Stage5'
-            }
-        }
-        steps {
-            echo "Stage5_8668106t : Work Release – Proceeds to Next Phase"
-        }
-    }
+        stage('Stage5') {
+            steps {
+                    script {
+                        if (env.STAGE_NAME == 'stage5') {
+                            sh "echo "Stage5_8668106t : Work Release – Proceeds to Next Phase"
+                        } else if (env.STAGE_NAME == 'stage4') {
+                            sh "echo  Stage5_8668106t : Work Release - Stops"
+                        }
+                    }
+                }
+              }
 }
+
